#!/usr/bin/env bash

fail() {
  echo "$1"
  exit 1
}

SITE_CONFIG_FILE_NAME=ef_site_config.py

# To build, set the env var SITE_CONFIG_FILE=(path to file ef_site_config.py)
# The file must be at ${SITE_CONFIG_FILE}/ef_site_config.py
# then ./build

# Example:
# export SITE_CONFIG_FILE=~/workspace/our_ef_repo/

[ -n "${SITE_CONFIG_FILE}" ] || fail "export SITE_CONFIG_FILE=path to ${SITE_CONFIG_FILE_NAME} before building"

SITE_CONFIG_FILE=${SITE_CONFIG_FILE}/${SITE_CONFIG_FILE_NAME}
[ -r ${SITE_CONFIG_FILE} ] || fail "can't read ${SITE_CONFIG_FILE_NAME} at ${SITE_CONFIG_FILE}"

cp ${SITE_CONFIG_FILE} src/${SITE_CONFIG_FILE_NAME} || fail "Error copying ${SITE_CONFIG_FILE}" to src/

./pants binary src:
