flyway.url=jdbc:mariadb://{{.SERVICE}}.rds.cx-{{.ENV}}.com
flyway.locations=filesystem:/srv/{{.SERVICE}}/db/{{.db_name}}

# Database to manage
flyway.schemas={{.db_name}}

# User to use to connect to the database.
flyway.user={{.db_user}}

# Password to use to connect to the database.
flyway.password={{.db_password}}
