version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install '.[test]'
      - run:
          command: python -m unittest discover
          name: Unit Tests
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID_ELLATIONENG
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_ELLATIONENG
      - run:
          command: aws s3 ls
          name: Test ellationeng aws
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID_ELLATION
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_ELLATION
      - run:
          command: aws s3 ls
          name: Test ellation aws
orbs:
  aws-cli: circleci/aws-cli@1.0.0
workflows:
  main:
    jobs:
      - build-and-test:
          context: aws
