version: 2.1


jobs:
  build-and-test:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          command: |
            curl https://ellation-cx-global-dist.s3-us-west-2.amazonaws.com/latebind/resolve-config -o resolve-config
            chmod +x resolve-config
workflows:
  main:
    jobs:
      - build-and-test
