version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install .
      - run: sudo python -m unittest discover
      - run:
          command: python setup.py test
          name: Unit Test
      - run:
          command: pylint --rcfile=./pylintrc ./efopn
          name: Pylint Test

workflows:
  main:
    jobs:
      - build-and-test
