version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install .
      - run: sudo pip install mock pylint
      - run:
          command: sudo python -m unittest discover
          name: Run Unit Test
      - run:
          command: pylint --rcfile=./pylintrc --disable=C,W,R ./efopen
          name: Run Pylint
workflows:
  main:
    jobs:
      - build-and-test
