version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install '.[test]'
      - run:
          command: python -m unittest discover
          name: Unit Tests
      - latebind/resolve-config:
          service: test-instance
orbs:
  latebind: crunchyroll/latebind@0.0.3
workflows:
  main:
    jobs:
      - build-and-test:
          context: aws
