#!/usr/bin/env bash

declare -r SITE_CONFIG_FILE_NAME=ef_site_config.py

fail() {
  echo "$1"
  exit 1
}

usage() {
  echo "$(basename $0) builds ef-open .pex files from source"
  echo -e "USAGE:\n  cd ~/workspace\n  build-ef-open <MY_INFRA_REPO>"
  echo -e "EXAMPLE:\n  cd ~/workspace\n  build-ef-open my-repo\n"
}

REPO=$1

[ -n "${REPO}" ] || fail "$(usage)"
[ -d "${REPO}" ] || fail "${REPO} is not a directory"
cd ${REPO}


SITE_CONFIG_FILESPEC=${SITE_CONFIG_PATH}/${SITE_CONFIG_FILE_NAME}
[ -r ${SITE_CONFIG_FILESPEC} ] || fail "can't read ${SITE_CONFIG_FILE_NAME} at ${SITE_CONFIG_PATH}"

cp ${SITE_CONFIG_FILESPEC} src/${SITE_CONFIG_FILE_NAME} || fail "Error copying ${SITE_CONFIG_FILESPEC}" to src/

# build
./pants binary src:
[ $? -eq 0 ] || fail "Build failed"

# rename files to remove .pex extension
for f in dist/*.pex; do
  mv "${f}" "${f%%.pex}"
done
