#!/usr/bin/env bash

fail() {
  echo "$1"
  echo -e "\nTo call:\n$ cd ~/workspace;
  exit 1
}

SITE_REPO=$1
SITE_CONFIG_FILE_NAME=ef_site_config.py


# To build, set the env var SITE_CONFIG_PATH=(path to file ef_site_config.py)
# The file must be at ${SITE_REPO}/ef_site_config.py
# then ./build


[ -n "${SITE_CONFIG_PATH}" ] || fail "export SITE_CONFIG_PATH=path to ${SITE_CONFIG_FILE_NAME} before building"

SITE_CONFIG_FILESPEC=${SITE_CONFIG_PATH}/${SITE_CONFIG_FILE_NAME}
[ -r ${SITE_CONFIG_FILESPEC} ] || fail "can't read ${SITE_CONFIG_FILE_NAME} at ${SITE_CONFIG_PATH}"

cp ${SITE_CONFIG_FILESPEC} src/${SITE_CONFIG_FILE_NAME} || fail "Error copying ${SITE_CONFIG_FILESPEC}" to src/

# build
./pants binary src:
[ $? -eq 0 ] || fail "Build failed"

# rename files to remove .pex extension
for f in dist/*.pex; do
  mv "${f}" "${f%%.pex}"
done
