#!/usr/bin/env bash

declare -r PANTS=./pants

fail() {
  echo -e "$1"
  exit 1
}

usage() {
  echo "$(basename $0) builds ef-open .pex files from source"
  echo -e "USAGE:\n  cd ~/workspace\n  ef-open/tools/build-ef-open"
  echo -e "EXAMPLE:\n  cd ~/workspace\n  ef-open/tools/build-ef-open\n"
}

[ -x "${PANTS}" ] || fail "No pants executable at ${PANTS}. Run this tool from the directory above all repos."

${PANTS} binary ef-open/src:
[ $? -eq 0 ] || fail "Build failed"

# rename files to remove .pex extension
for f in dist/*.pex; do
  mv "${f}" "${f%%.pex}"
done
