name: gitleaks

on: [pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: gitleaks-action
      name: gitleaks-action
      uses: crunchyroll/gitleaks-action@master
